# Generated by Django 4.1.6 on 2023-05-05 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringEstablishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('balance', models.FloatField(default=0, editable=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('last_payment_datetime', models.DateTimeField(null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CateringEstablishmentSpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'catering_establishment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='catering_establishment.cateringestablishment'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='SpecialOfferParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                (
                    'catering_establishment_special_offer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='catering_establishment.cateringestablishmentspecialoffer',
                    ),
                ),
                (
                    'participant',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False)),
                (
                    'catering_establishments',
                    models.ManyToManyField(
                        related_name='special_offers',
                        through='catering_establishment.CateringEstablishmentSpecialOffer',
                        to='catering_establishment.cateringestablishment',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='CateringEstablishmentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('serving_clients_number', models.IntegerField()),
                (
                    'catering_establishment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tables',
                        to='catering_establishment.cateringestablishment',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='cateringestablishmentspecialoffer',
            name='special_offer',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='catering_establishment.specialoffer'
            ),
        ),
        migrations.CreateModel(
            name='CateringEstablishmentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                (
                    'catering_establishment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ratings',
                        to='catering_establishment.cateringestablishment',
                    ),
                ),
                (
                    'visitor',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name='CateringEstablishmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='catering_establishment/photos/')),
                (
                    'catering_establishment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='photos',
                        to='catering_establishment.cateringestablishment',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='CateringEstablishmentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
                ),
                ('feedback', models.TextField()),
                (
                    'catering_establishment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='feedbacks',
                        to='catering_establishment.cateringestablishment',
                    ),
                ),
                (
                    'visitor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='feedbacks',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CateringEstablishmentBalanceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('transaction_datetime', models.DateTimeField()),
                (
                    'catering_establishment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='balance_changes',
                        to='catering_establishment.cateringestablishment',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='BookingConditions',
            fields=[
                ('id', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False)),
                ('catering_establishment', models.ManyToManyField(to='catering_establishment.cateringestablishment')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                (
                    'catering_establishment_table',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='bookings',
                        to='catering_establishment.cateringestablishmenttable',
                    ),
                ),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
