# Generated by Django 4.1.6 on 2023-05-07 18:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('catering_establishment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cateringestablishmentfeedback',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='cateringestablishmentfeedback',
            unique_together={('catering_establishment', 'feedback')},
        ),
        migrations.AlterUniqueTogether(
            name='cateringestablishmentrating',
            unique_together={('catering_establishment', 'rating')},
        ),
    ]
