# Generated by Django 4.1.6 on 2023-05-17 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('catering_establishment', '0002_alter_cateringestablishmentfeedback_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='cateringestablishment',
            name='last_payment_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cateringestablishment',
            name='work_hours',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to='catering_establishment.workhours'
            ),
        ),
    ]
