# Generated by Django 4.1.6 on 2023-06-01 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('catering_establishment', '0005_bookingpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpayment',
            name='booking',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='booking_payment',
                to='catering_establishment.booking',
            ),
        ),
    ]
