# Generated by Django 4.1.6 on 2023-06-04 18:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catering_establishment', '0006_alter_bookingpayment_booking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cateringestablishmentrating',
            unique_together={('catering_establishment', 'visitor')},
        ),
    ]
