# Generated by Django 4.1.6 on 2023-06-05 07:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('catering_establishment', '0007_alter_cateringestablishmentrating_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cateringestablishmentfeedback',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterUniqueTogether(
            name='cateringestablishmentfeedback',
            unique_together=set(),
        ),
    ]
