# Generated by Django 4.1.6 on 2023-06-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catering_establishment', '0008_alter_cateringestablishmentfeedback_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringestablishment',
            name='number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
