# Generated by Django 4.1.6 on 2023-06-05 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('catering_establishment', '0009_cateringestablishment_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cateringestablishment',
            old_name='number',
            new_name='enterprise_number',
        ),
    ]
