default_language_version:
    python: python3.10

repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        additional_dependencies: ["black==23.1.0"]
        types: [python]
        args: [--line-length=120, -S]
      - id: isort
        name: isort
        entry: isort
        language: python
        additional_dependencies: ["isort==5.11.5"]
        types: [python]
        args: [--check-only]
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        additional_dependencies: ["flake8==6.0.0"]
        types: [python]
        args: [--max-line-length=120]
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        exclude: migrations/
        types: [python]
        args: [--ignore=migrations]
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
