# Generated by Django 4.1.6 on 2023-05-28 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('catering_establishment', '0004_alter_cateringestablishment_work_hours'),
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                (
                    'booking',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering_establishment.booking'),
                ),
                (
                    'dish',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dish.cateringestablishmentdish'),
                ),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
