# Generated by Django 4.1.6 on 2023-05-28 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dish', '0002_ordereddish_delete_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereddish',
            old_name='dish',
            new_name='catering_establishment_dish',
        ),
    ]
