# Generated by Django 4.1.6 on 2023-05-28 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('catering_establishment', '0004_alter_cateringestablishment_work_hours'),
        ('dish', '0003_rename_dish_ordereddish_catering_establishment_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereddish',
            name='booking',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ordered_dishes',
                to='catering_establishment.booking',
            ),
        ),
        migrations.AlterField(
            model_name='ordereddish',
            name='catering_establishment_dish',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ordered_dishes',
                to='dish.cateringestablishmentdish',
            ),
        ),
    ]
